### ISSUE TITLE
setup.py gone?

### ISSUE THREAD

**Issue by MaxNoe** [jacquemier/pyhessioxxx#1]
In 6ef976e0ec361bbc2bdb you deleted the `setup.py`.

Was this maybe accidentally? Because the commit message says `mv` and not `rm`

**Comment by jacquemier** [comment]
A lot of changes has been done on hessioxxx Python wrapper, thanks to you.
And we decided to move it on cta-observatory repository:
https://github.com/cta-observatory/pyhessio

This repository will be deleted soon.


So please move to this new repo/version of pyhessio
Installation instruction can be found here:
https://github.com/cta-observatory/pyhessio
